-- Table: user
/*
summary: Stores information about users, including their assigned roles and work modules.
*/
CREATE TABLE IF NOT EXISTS user (
    userId UUID NOT NULL PRIMARY KEY DEFAULT UUID(), -- Unique identifier for each user, generated by default
    userRoleId UUID NOT NULL, -- ID of the role assigned to the user (cannot be null)
    userWorkModuleId UUID NOT NULL, -- ID of the work module assigned to the user (cannot be null)
    nickname VARCHAR(50) NOT NULL UNIQUE, -- User's nickname (cannot be null), must be unique
    name VARCHAR(30), -- User's first name
    lastname VARCHAR(30), -- User's last name
    description VARCHAR(500), -- Description of the user
    password VARCHAR(256) NOT NULL, -- User's password (cannot be null)
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP, -- Date and time when the user record was created
    isActive BOOLEAN DEFAULT TRUE, -- Indicates if the user is active (default is TRUE)
    CONSTRAINT Fk_userRoleId_user FOREIGN KEY(userRoleId) REFERENCES user_role(userRoleId), -- Foreign key constraint referencing user_role table
    CONSTRAINT Fk_userWorkModuleId_user FOREIGN KEY(userWorkModuleId) REFERENCES user_work_module(userWorkModuleId) -- Foreign key constraint referencing user_work_module table
) ENGINE=INNODB;
